import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { Layout } from '../components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ty Carlson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Layout>
        <h1>404 - sorry couldn&lsquo;t find that one.</h1>
        <Link href="/">&larr; home</Link>
      </Layout>
    </>
  );
};

export default Home;
