import type { NextPage } from 'next';
import Head from 'next/head';

import { Layout } from '../components';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Layout>
        <main className={styles.main}>
          <h1 className={styles.title}>404</h1>
        </main>
      </Layout>
    </>
  );
};

export default Home;
