import type { NextPage } from 'next';
import Head from 'next/head';

import { Layout } from '../components';

const Photos: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1>Photos</h1>
      </Layout>
    </>
  );
};

export default Photos;
