import { useCallback, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Rowengartner.module.css';

const Parts = [
  ['Rulen', 'Raven', 'Rosen', 'Roven', 'Roger', 'Rowen', 'Runna', 'Rollin'],
  ['verter', 'boozer', 'gagger', 'grueter', 'grooten', 'gardener', 'gartner', 'mucker', 'fruiter'],
];

function getRandom(arr: string[]) {
  return Math.floor(Math.random() * arr.length);
}

type Props = {
  part1: string;
  part2: string;
};

const Rowengartner: NextPage<Props> = ({ part1, part2 }) => {
  const [partOne, setPartOne] = useState(part1);
  const [partTwo, setPartTwo] = useState(part2);

  const handleOnClick = useCallback(() => {
    setPartOne(Parts[0][getRandom(Parts[0])]);
    setPartTwo(Parts[1][getRandom(Parts[1])]);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <article
        onClick={handleOnClick}
        className={styles.wrapper}
        style={{
          background: "url( '/henry.jpg' ) top center no-repeat",
          backgroundSize: 'cover',
        }}
      >
        <div>
          <h1 className={styles.title}>
            Henry <span id="part_one">{partOne}</span>
            <span id="part_two">{partTwo}</span>
          </h1>
        </div>
      </article>
    </>
  );
};

export async function getServerSideProps() {
  const part1 = Parts[0][getRandom(Parts[0])];
  const part2 = Parts[1][getRandom(Parts[1])];

  return { props: { part1, part2 } };
}

export default Rowengartner;
